# Generated by Django 5.2.1 on 2025-05-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Orden de Compra')),
                ('nombre_producto', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Almacén',
                'verbose_name_plural': 'Productos de Almacén',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
