# Generated by Django 5.2.1 on 2025-05-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='cantidad_pedida',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Pedida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='cantidad_surtida',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Ya Surtida'),
        ),
    ]
