# Generated by Django 5.2.1 on 2025-05-30 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('encargado_obra', models.CharField(max_length=150, verbose_name='Encargado de Obra')),
                ('fecha_estimada_entrega', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Estimada de Entrega')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_estimada_entrega', 'nombre_obra'],
            },
        ),
    ]
