# Generated by Django 5.2.1 on 2025-06-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosdjango', '0002_alter_customuser_groups_and_more'),
        ('usuariosdjango', '0003_crear_superuser_inicial'),
    ]

    operations = [
    ]
